[Client]

# Group: Others
"Enable mod" = false
"Enable Cloud Sync" = true
"Enable dynamic light" = true
"Hide backpack if invisible" = true

[style]

# Group: Others
"Backpack Model Type" = "backtools"
"Variant" = "default"

[Server]

# Group: Others
"Hide items component data" = false

