# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"
# The chunk rebuild scheduler mode (immediate, culling).
chunk_rebuild_scheduler = "culling"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enables dynamic lighting of beacon or end gateway beams.
	beam = true
	# Enables dynamic lighting of firefly particles from Firefly Bushes.
	firefly = true
	# Enables dynamic lighting for entities that have the Glowing effect.
	glowing_effect = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enables dynamic lighting of the Warden's sonic boom attack particles.
	sonic_boom = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# Enables dynamic lighting of Guardian's lasers. This also can be toggled off by disabling Guardian dynamic lighting.
	guardian_laser = true

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				tnt = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				tropical_fish = true
				chest_minecart = true
				slime = true
				pillager = true
				area_effect_cloud = true
				blaze = true
				piglin = true
				end_crystal = true
				endermite = true
				zombie = true
				ender_pearl = true
				item_display = true
				breeze_wind_charge = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				block_display = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				cod = true
				snow_golem = true
				witch = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armadillo = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				vex = true
				wandering_trader = true
				wither_skeleton = true
				piglin_brute = true
				breeze = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				shulker_bullet = true
				squid = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				bogged = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				wind_charge = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				ominous_item_spawner = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.fallingtrees]
				tree = true

			[light_sources.settings.entities.spell_engine]
				spell_projectile = true
				spell_area_effect = true

			[light_sources.settings.entities.endermanoverhaul]
				flower_fields_enderman = true
				coral_enderman = true
				ender_bullet = true
				windswept_hills_enderman = true
				icy_pearl = true
				summoner_pearl = true
				nether_wastes_enderman = true
				soul_pearl = true
				mushroom_fields_enderman = true
				snowy_enderman = true
				soulsand_valley_enderman = true
				axolotl_pet_enderman = true
				hammerhead_pet_enderman = true
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				spirit = true
				ancient_pearl = true
				end_enderman = true
				corrupted_pearl = true
				bubble_pearl = true
				crimson_forest_enderman = true
				warped_pearl = true
				cave_enderman = true
				dark_oak_enderman = true
				crimson_pearl = true
				end_islands_enderman = true
				scarab = true
				swamp_enderman = true
				badlands_enderman = true
				warped_forest_enderman = true
				pet_enderman = true

			[light_sources.settings.entities.amendments]
				medium_dragon_fireball = true
				falling_lantern = true
				medium_fireball = true

			[light_sources.settings.entities.snowyspirit]
				gingerbread_golem = true
				container_entity = true
				sled = true
				gingerbread_giant = true

			[light_sources.settings.entities.another_furniture]
				seat = true

			[light_sources.settings.entities.bountifulfares]
				flour = true

			[light_sources.settings.entities.rottencreatures]
				frostbitten = true
				immortal = true
				mummy = true
				hunter_wolf = true
				zap = true
				undead_miner = true
				glacial_hunter = true
				swampy = true
				burned = true
				primed_tnt_barrel = true
				dead_beard = true
				skeleton_lackey = true
				zombie_lackey = true
				scarab = true

			[light_sources.settings.entities.immersive_aircraft]
				airship = true
				bamboo_hopper = true
				cargo_airship = true
				warship = true
				gyrodyne = true
				quadrocopter = true
				biplane = true
				tiny_tnt = true
				bullet = true

			[light_sources.settings.entities.ribbits]
				ribbit = true

			[light_sources.settings.entities.ecologics]
				squirrel = true
				chest_boat = true
				boat = true
				penguin = true
				coconut_crab = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				package = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.yungscavebiomes]
				sand_snapper = true
				icicle = true
				ice_cube = true

			[light_sources.settings.entities.crittersandcompanions]
				dragonfly = true
				jumping_spider = true
				leaf_insect = true
				shima_enaga = true
				koi_fish = true
				dumbo_octopus = true
				grappling_hook = true
				ferret = true
				otter = true
				sea_bunny = true
				red_panda = true

			[light_sources.settings.entities.xercapaint]
				canvas = true
				easel = true

			[light_sources.settings.entities.elixirum]
				thrown_elixir = true

			[light_sources.settings.entities.sophisticatedbackpacks]
				everlasting_backpack_item = true

			[light_sources.settings.entities.descendants_weaponry]
				projectile_golden_trident_thrown = true
				projectile_stone_trident_thrown = true
				projectile_diamond_trident_thrown = true
				projectile_wooden_trident_thrown = true
				projectile_iron_trident_thrown = true
				projectile_netherite_trident_thrown = true

			[light_sources.settings.entities.wildernature]
				deer = true
				cassowary = true
				owl = true
				pelican = true
				termite = true
				flamingo = true
				boar = true
				raccoon = true
				red_wolf = true
				squirrel = true
				hedgehog = true
				turkey = true
				minisheep = true
				bullet = true
				bison = true
				dog = true
				penguin = true

			[light_sources.settings.entities.creeperoverhaul]
				swamp_creeper = true
				bamboo_creeper = true
				jungle_creeper = true
				beach_creeper = true
				cave_creeper = true
				savannah_creeper = true
				hills_creeper = true
				spruce_creeper = true
				birch_creeper = true
				snowy_creeper = true
				badlands_creeper = true
				ocean_creeper = true
				dark_oak_creeper = true
				desert_creeper = true
				dripstone_creeper = true
				mushroom_creeper = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				sludge = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				angler_fish = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.smallships]
				ground_cannon = true
				galley = true
				brigg = true
				drakkar = true
				cog = true
				cannon_ball = true

			[light_sources.settings.entities.exposure]
				glass_photograph_frame = true
				camera_stand = true
				photograph_frame = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.winteroverhaul]
				robin = true

			[light_sources.settings.entities.golemoverhaul]
				hay_golem = true
				netherite_golem = true
				terracotta_golem = true
				candle_flame = true
				mud_ball = true
				coal_golem = true
				honey_golem = true
				barrel_golem = true
				honey_blob = true
				kelp_golem = true
				candle_golem = true
				slime_golem = true

			[light_sources.settings.entities.farm_and_charm]
				plow = true
				chair = true
				rotten_tomato = true
				cart = true

			[light_sources.settings.entities.dungeonsdelight]
				rancid_reduction = true
				zombified_dryad = true
				monster_yam = true
				ancient_egg = true
				echo_blast = true
				gunk_arrow = true
				cleaver = true

			[light_sources.settings.entities.hybrid-aquatic]
				tetra = true
				octopus = true
				vampire_crab = true
				karcinoma = true
				flower_crab = true
				mackerel = true
				anglerfish = true
				sea_nettle = true
				lantern_shark = true
				lions_mane_jellyfish = true
				rockfish = true
				oscar = true
				tiger_shark = true
				sea_bass = true
				betta = true
				dragonfish = true
				pearlfish = true
				carp = true
				flashlight_fish = true
				hound_shark = true
				stonefish = true
				parrotfish = true
				needlefish = true
				damselfish = true
				ghost_crab = true
				moon_jellyfish = true
				crayfish = true
				spider_crab = true
				hammerhead_shark = true
				stingray = true
				otter = true
				cuttlefish = true
				discus = true
				dungeness_crab = true
				crown_jellyfish = true
				nomura_jellyfish = true
				pupfish = true
				john_dory = true
				arrow_squid = true
				coconut_crab = true
				lionfish = true
				triggerfish = true
				ratfish = true
				sea_angel = true
				coelacanth = true
				sea_slug = true
				hermit_crab = true
				firefly_squid = true
				blowfish = true
				great_white_shark = true
				sea_cucumber = true
				fiddler_crab = true
				barrel_jellyfish = true
				sea_urchin = true
				tiger_barb = true
				african_butterflyfish = true
				herring = true
				squirrelfish = true
				bull_shark = true
				barreleye = true
				seahorse = true
				firework_jellyfish = true
				lightfoot_crab = true
				piranha = true
				mahi = true
				lobster = true
				gourami = true
				nautilus = true
				basking_shark = true
				karkinos = true
				karcinogen = true
				surgeonfish = true
				mauve_stinger = true
				tuna = true
				shrimp = true
				whale_shark = true
				vampire_squid = true
				seadragon = true
				clownfish = true
				goldfish = true
				box_jellyfish = true
				thresher_shark = true
				yeti_crab = true
				umbrella_octopus = true
				danio = true
				wrasse = true
				starfish = true
				blue_jellyfish = true
				big_red_jellyfish = true
				flying_fish = true
				barracuda = true
				oarfish = true
				giant_isopod = true
				golden_dorado = true
				manta_ray = true
				snailfish = true
				horseshoe_crab = true
				cosmic_jellyfish = true
				boxfish = true
				decorator_crab = true
				sunfish = true
				cepheidae_jellyfish = true
				opah = true
				frilled_shark = true
				moray_eel = true

[debug]
	active_dynamic_lighting_cells = false
	display_dynamic_lighting_chunk_rebuild = false
	display_behavior_bounding_box = false

[adaptive_ticking]
	# Reduces how often sources behind the camera get ticked.
	background_sleep = true
	# How far away (in chunks) until light sources get ticked less often.
	slow = 5
	# How far away (in chunks) until light sources get ticked even less often.
	slower = 8
