[general]

# Group: Server side
"Disable ability to ride" = false

# Group: Client side
"Translucent rider in 1st person view" = 100			# 0 to disable render player model
"Translucent carrier in 1st person view" = 100			# 0 to disable render player model
"Dismount on falling" = false
"Carrying Causes Hunger" = false
"Weighted Carrying" = false

