removeSavannaAnimals = true
removeSwampAnimals = true
removeJungleAnimals = true
removeForestAnimals = true
addJungleAnimals = true
spawnHazelnutBush = true
# Default: 5
# Range: 0 ~ 1000
pelicanSpawnWeight = 5
# Default: 3
# Range: 1 ~ 10
pelicanMinGroupSize = 3
# Default: 5
# Range: 1 ~ 10
pelicanMaxGroupSize = 5
# Default: 12
# Range: 0 ~ 1000
deerSpawnWeight = 12
# Default: 2
# Range: 1 ~ 10
deerMinGroupSize = 2
# Default: 4
# Range: 1 ~ 10
deerMaxGroupSize = 4
# Default: 8
# Range: 0 ~ 1000
raccoonSpawnWeight = 8
# Default: 2
# Range: 1 ~ 10
raccoonMinGroupSize = 2
# Default: 3
# Range: 1 ~ 10
raccoonMaxGroupSize = 3
# Default: 8
# Range: 0 ~ 1000
squirrelSpawnWeight = 8
# Default: 2
# Range: 1 ~ 10
squirrelMinGroupSize = 2
# Default: 2
# Range: 1 ~ 10
squirrelMaxGroupSize = 2
# Default: 10
# Range: 0 ~ 1000
redWolfSpawnWeight = 10
# Default: 2
# Range: 1 ~ 10
redWolfMinGroupSize = 2
# Default: 4
# Range: 1 ~ 10
redWolfMaxGroupSize = 4
# Default: 12
# Range: 0 ~ 1000
owlSpawnWeight = 12
# Default: 3
# Range: 1 ~ 10
owlMinGroupSize = 3
# Default: 3
# Range: 1 ~ 10
owlMaxGroupSize = 3
# Default: 14
# Range: 0 ~ 1000
boarSpawnWeight = 14
# Default: 4
# Range: 1 ~ 10
boarMinGroupSize = 4
# Default: 5
# Range: 1 ~ 10
boarMaxGroupSize = 5
# Default: 10
# Range: 0 ~ 1000
bisonSpawnWeight = 10
# Default: 3
# Range: 1 ~ 10
bisonMinGroupSize = 3
# Default: 5
# Range: 1 ~ 10
bisonMaxGroupSize = 5
# Default: 12
# Range: 0 ~ 1000
turkeySpawnWeight = 12
# Default: 3
# Range: 1 ~ 10
turkeyMinGroupSize = 3
# Default: 5
# Range: 1 ~ 10
turkeyMaxGroupSize = 5
# Default: 2
# Range: 0 ~ 1000
dogSpawnWeight = 2
# Default: 1
# Range: 1 ~ 10
dogMinGroupSize = 1
# Default: 1
# Range: 1 ~ 10
dogMaxGroupSize = 1
# Default: 8
# Range: 0 ~ 1000
minisheepSpawnWeight = 8
# Default: 2
# Range: 1 ~ 10
minisheepMinGroupSize = 2
# Default: 4
# Range: 1 ~ 10
minisheepMaxGroupSize = 4
# Default: 10
# Range: 0 ~ 1000
penguinSpawnWeight = 10
# Default: 2
# Range: 1 ~ 10
penguinMinGroupSize = 2
# Default: 5
# Range: 1 ~ 10
penguinMaxGroupSize = 5
# Default: 12
# Range: 0 ~ 1000
cassowarySpawnWeight = 12
# Default: 3
# Range: 1 ~ 10
cassowaryMinGroupSize = 3
# Default: 4
# Range: 1 ~ 10
cassowaryMaxGroupSize = 4
# Default: 9
# Range: 0 ~ 1000
flamingoSpawnWeight = 9
# Default: 3
# Range: 1 ~ 10
flamingoMinGroupSize = 3
# Default: 6
# Range: 1 ~ 10
flamingoMaxGroupSize = 6
# Default: 10
# Range: 0 ~ 1000
hedgehogSpawnWeight = 10
# Default: 2
# Range: 1 ~ 10
hedgehogMinGroupSize = 2
# Default: 4
# Range: 1 ~ 10
hedgehogMaxGroupSize = 4
